### ISSUE TITLE
sh: 1: mecab-config not found

### ISSUE THREAD

**Issue by yoshitakahashi** [mcho421/noj#2]
When installing the python package I hit an error when running the command 'sudo python setup.py install'.  The mecab-config file is not found making it so it is impossible to finish setup.  Here is a copy of the error message:

sh: 1: mecab-config: not found
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    version = cmd1("mecab-config --version"),
  File "setup.py", line 7, in cmd1
    return os.popen(str).readlines()[0][:-1]

Please respond if you have any solution to this issue, thanks!

＜日本語訳(Japanese Translation)＞
pythonパッケージをインストールしている際、sudo python setup.py installのコマンドを入力すると、エラーが表示されました。Mecab-configのファイルが見つからず、セットアップを行うことができません。エラーメッセージを上に記入させていただきました。問題の解決方法を教えて頂ければ幸いです。何卒宜しくお願い致します。

**Comment by mcho421** [comment]
Hi @yoshitakahashi,
Thanks for trying out this project! How did you find it by the way?

Could you tell me what operating system you're using?
Can you try `which mecab--config` to see if it exists?

If it does, maybe try configuring the ipadic with
`./configure --with-mecab-config=your/path/to/mecab-config --with-charset=utf8`

Let me know if you have any more problems.

See this for more information:
http://d.hatena.ne.jp/hase1031/20111005/1317808636

**Comment by yoshitakahashi** [comment]
I fixed the problem. Thank you very much!

**Comment by tayfun** [comment]
If you're installing MeCab via a package manager, be sure to get `libmecab-dev` to get `mecab-config` too.
